### ISSUE TITLE
stage 

### ISSUE THREAD

**Issue by wansingcheng** [ritwickdey/live-server-web-extension#104]
the User Needs Survey of Dev Tools https://docs.google.com/forms/d/e/1FAIpQLSfObQ3llRl4W1rYNiKBzF8FaLI_jCy0UUEUC9tRlj3oDRlRPQ/viewform

Share From App: Dev Tools(Android Developer Tools)

[]()![mmexport1679626366665.jpg](https://user-images.githubusercontent.com/77646914/227822806-a9c77fab-0945-41a3-a8b4-f9d64fad448f.jpg)

**Comment by YioHands** [comment]
Devuélveme la página Calistenicos de la casa cuanto antes el karma es el
peor enemigo de todos. No quiero tomar medidas extremas gusano del averno.
