### ISSUE TITLE
Reload on localhost/php not changing the content

### ISSUE THREAD

**Issue by KevinNowalski** [ritwickdey/live-server-web-extension#15]
I have a php file in localhost/php named index.php with this code: 

echo "Hello world!<br>";
echo "Hello world 2!<br>";

My actual server address: http://localhost/php/
My live server address: http://127.0.0.1:5500/

but  when I change my index.php code and save, the new code does not refresh in the browser of http://localhost/php/ like on the ritwickdey YouTube video.  I used firefox and chrome web extensions.  What am I missing?

**Comment by Mikael-Sundstrom** [comment]
Hi, I have just updated the documentation. Can you check if you have missed [Step 5](https://github.com/ritwickdey/live-server-web-extension/blob/master/docs/Setup.md#direct-setup) that I added now.
You have to put your app on the `http://localhost/php/` location.

Let me know if you've tried it. If it doesn't work, I want to help you figure it out so I can update the documentation further to clarify the misunderstandings.

**Comment by KevinNowalski** [comment]
I put index.php in the php folder on http://localhost/php.  Still no change.

**Comment by KevinNowalski** [comment]
I got it to work for Firefox and Chrome!  All I did was reinstall the extension for both and it works with the steps listed.  Thanks.

**Comment by Mikael-Sundstrom** [comment]
It's good to hear and thank you for the feedback! I hope you get a good experience of this add-on.

**Comment by FaycalBESS** [comment]
Hello, i set-up every thing as described in the steps given but still not work, 
Actually, it worked with the test file and when I umped to production files... nothing
I reviewd all the steps many time
any chages in the meanwhile?
(mac os catalina 10.15.6 / Mamp Pro 5.7 / VS Code 1.47.2 / Live-server 1.3.0)

**Comment by hackingoffice127-create** [comment]
http://127.0.0.1:8828
