### ISSUE TITLE
Reload all tabs after save project in vscode

### ISSUE THREAD

**Issue by VasyaHH** [ritwickdey/live-server-web-extension#16]
After update to version 1.2.0 and fix this issue (https://github.com/ritwickdey/vscode-live-server/issues/127) I have a problem. When I save file in vscode all tabs automaticaly reload, but I need to reload only current dev page, not google search results.

**Comment by ritwickdey** [comment]
Are you sure? I just tried, it is working perfectly. 

Anyway, which browser you're using? And try to close the browser & remove all server address from the pop up menu & again enter everything... 

Let me know if it works or not.

**Comment by VasyaHH** [comment]
I am using Chrome 66 (Version 66.0.3359.170 (Official Build) (64-bit))
Step to reproduce bug:
1. Click "Go Live" button on vscode status bar 
![image](https://user-images.githubusercontent.com/22713298/40232394-44b95fb6-5aa7-11e8-96f0-b7b0e8dcf050.png)

2. Start chrome
3. Open google.com
4. Turn on live reload
5. Hit Ctrl+S on vscode editor
And google.com page will be reloaded
Extension settings:
![image](https://user-images.githubusercontent.com/22713298/40232376-30d48728-5aa7-11e8-9d14-8a53109a23f6.png)

**Comment by ritwickdey** [comment]
OMG! I found the bug! What a bad day is going with me. 

This bug is opened from https://github.com/ritwickdey/live-server-web-extension/commit/4f5d293bf68e12b13966cbf171bb4e8ab274b2a6

**Comment by ritwickdey** [comment]
Thanks again.
I've pushed a new version with `v1.3.0`. It will be visible to store within 60 min. 

Let me know, if it works or not.

**Comment by ritwickdey** [comment]
This bug has been fixed. Let me know if it not works. 👍
