### ISSUE TITLE
PHP Still Downloading

### ISSUE THREAD

**Issue by PhyberOptik** [ritwickdey/live-server-web-extension#24]
I have looked at every example and every comment and the .php files will not work.  Is there any way you can create a solid video and post it?

**Comment by PhyberOptik** [comment]
Disregard, I figured out the issue. I had an error on the vsCode settings.json file.

**Comment by mrkhew** [comment]
Could you point out the error because I'm encountering the same issue as yours.

**Comment by Taariqq** [comment]
> Disregard, I figured out the issue. I had an error on the vsCode settings.json file.

I am having the same issue ... .php file just keeps giving option to download. My Brackets editor is unable to handle WordPress php files. Otherwise I would not need this.
