### ISSUE TITLE
Windows Defender warning

### ISSUE THREAD

**Issue by eijoac** [ritwickdey/live-server-web-extension#26]
I got a threat report for the index.min.js file from my Windows Defender (see screenshot below). Is it mistake from the Defender?

![image](https://user-images.githubusercontent.com/10935026/50252154-1bfbe380-03b4-11e9-9072-f0b7b2e802fa.png)

Update: looked into it a bit more. I guess it's related to this: https://snyk.io/blog/a-post-mortem-of-the-malicious-event-stream-backdoor, and has been fixed/updated.

**Comment by SapereaudeForest** [comment]
Same for me 
From Kaspersky 
18/01/2019 11:38:53	Quarantined	Trojan program HEUR:Trojan.Script.Generic	C:\Users\*****\.vscode\extensions\ritwickdey.liveserver-5.2.0\node_modules\flatmap-stream\test\data.js	High

**Comment by ritwickdey** [comment]
Upgrade to latest version.
