### ISSUE TITLE
live server not working on windows machine.

### ISSUE THREAD

**Issue by Edmund1645** [ritwickdey/live-server-web-extension#33]
I started using live server VSCode extension for development but it doesn't auto reload in browser, i tried with the live reload extension and still doesn't work. But when i use it on my Linux VM it works fine even without the chrome extension. I don't work with php, I work with static html.

**Comment by Mikael-Sundstrom** [comment]
You don't need this browser add-on for static HTML. You only need the VS Code-extension for that. 

You will find the repository here: [VS Code Extension on GitHub](https://github.com/ritwickdey/vscode-live-server)

**Comment by Edmund1645** [comment]
I was using the VS Code-extension alone but it still wasn't working, the live reload feature doesn't work, but it works on my Linux VM.

**Comment by Mikael-Sundstrom** [comment]
It's hard to help here. Can you open an issue in the VS Code Extension repository instead, because the issue is in the code editor extension, and not the browser add-on?

**Comment by Edmund1645** [comment]
Alright.
