### ISSUE TITLE
Basic Routing

### ISSUE THREAD

**Issue by BinaryBen** [ritwickdey/live-server-web-extension#5]
I haven't had a chance to play with this extension - so I am sorry if this already exists. If I were to use this to develop a SPA, I would need to be able to ensure all routes are redirected to index.html (unless the file otherwise exists, i.e. for stylesheets and js files). Then I can use something like page.js (or whatever framework is the flavour of the month) to handle routing.

Does this exist / is this otherwise possible?

**Comment by ritwickdey** [comment]
It should be issue of https://github.com/ritwickdey/vscode-live-server/issues. 

Can you able to create issue request on here https://github.com/ritwickdey/vscode-live-server/issues ?

**Comment by BinaryBen** [comment]
Sorry, didn't mean to put it in the wrong one. Done > ritwickdey/vscode-live-server#39
