### ISSUE TITLE
Doesn't work on Mozilla

### ISSUE THREAD

**Issue by RobyCigar** [ritwickdey/live-server-web-extension#61]
![Screenshot from 2021-03-13 15-12-46](https://user-images.githubusercontent.com/69680330/111024010-e9b08380-840e-11eb-8f89-f6075cd17dc1.png)

I already open my PHP port on localhost:8000 but why it is still doesnt work? , 
thank you :)

**Comment by mricim** [comment]
There could be a million reasons and with the little information you gave it is impossible to help you. I would appreciate more information.
For example:
What server do you use?
When following the [Setup](https://github.com/ritwickdey/live-server-web-extension/blob/master/docs/Setup.md) point by point, did you have any problem?
Did you make sure to load your application on the server path and check that it worked?
