### ISSUE TITLE
Couldn't find this extension in chrome web store

### ISSUE THREAD

**Issue by alifirhas** [ritwickdey/live-server-web-extension#63]
I followed the link to install the extension on the chrome web store which is in the documentation of this extension but it all goes to the 404 page.

![Screenshot from 2021-04-26 22-45-09](https://user-images.githubusercontent.com/32509276/116112420-bd607600-a6e1-11eb-88f4-b77ece0f4d32.png)

Then i realized after many tries that the README.md on the main page of the extension for chrome from this repository is not found either.

Does anyone know how to install this extension without chrome webs tore?

**Comment by jslalriya** [comment]
Yeah, it looks like he took if off from the web stores.

**Comment by mricim** [comment]
(Help for fast googler)
It can be installed directly without the need for the chrome web store. I recommend not doing it for security reasons and that it is a bit annoying, but as a temporary solution it is fine.

Steps:
- Go to [extensions](chrome://extensions/)
- Activate developer mode
- Press the "Load unzipped" button.
- (Optional) "Fix" the extension in the menu, so as not to lose sight of it. It can be done from this icon, next to the browser bar
![image](https://user-images.githubusercontent.com/56126432/116301106-f828e380-a79f-11eb-9b3e-059904289178.png)

**Comment by alifirhas** [comment]
Thank you, that do the work. But man the installation fell a bit nasty.

**Comment by mricim** [comment]
I would not have closed the issue.  It is still a problem that the installer they provide you does not work

**Comment by alifirhas** [comment]
Oh sorry, i trully forget the root cause of this issue

**Comment by ritwickdey** [comment]
Permission issue from Google.

**Comment by acicovic** [comment]
@ritwickdey is this solvable?

**Comment by ritwickdey** [comment]
No. I've submitted the extension 3 times for review. They are asking why I'm using "Tabs" permission. I told them that I need to refresh all matches (eg. localhost) tabs. But still, they are asking to remove the permission. Let me check without permission.

**Comment by ritwickdey** [comment]
![image](https://user-images.githubusercontent.com/18099464/116786361-d2f7e600-aabb-11eb-9486-af77c4aea0b8.png)
Submitted for review again after removing tabs permission. Lets wait for 2 days.

**Comment by acicovic** [comment]
The Chrome Web Store page works for me now:

https://chrome.google.com/webstore/detail/live-server-web-extension/fiegdmejfepffgpnejdinekhfieaogmj/

**Comment by alifirhas** [comment]
@acicovic Okay, since the root cause of this issue is resolved so I will close this issue
